# Generated by Django 3.2.4 on 2021-06-09 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doska', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='icons/'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='doska.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активация'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='price',
            field=models.PositiveIntegerField(help_text='0 = Договорная', verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='valute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='doska.valute', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='upload_images/', verbose_name='Изображение'),
        ),
    ]
