# Generated by Django 3.2.4 on 2021-06-11 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doska', '0003_auto_20210611_0622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Регион', 'verbose_name_plural': 'Регионы'},
        ),
    ]
