# Generated by Django 3.2.4 on 2021-06-16 04:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doska', '0005_alter_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='image',
        ),
    ]
