# Generated by Django 3.2.4 on 2021-06-21 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doska', '0006_remove_ad_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='content',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='ad',
            name='valute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doska.valute', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='upload_images/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
