# Generated by Django 3.2.4 on 2021-07-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doska', '0009_auto_20210722_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyitem',
            name='story_type',
            field=models.CharField(choices=[('mp4', 'video'), ('jpg', 'image')], default='null', max_length=300),
            preserve_default=False,
        ),
    ]
