# Generated by Django 3.2.4 on 2021-08-10 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doska', '0012_auto_20210809_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car_Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='test_media2/')),
            ],
        ),
    ]
